# Run make action

name: Build

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: make clean
        run: | 
          make clean
      - name:  make verbose
        run: |
          make verbose
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
