# Test disassembled code produced by the emulator

name: Test Disassembler

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  test-disassembly: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Build the emulator
        run: |
          make
      - name: Assemble test files
        run: | 
          cd tools
          chmod +x ./zasm
          ./zasm --ixcbr2 test_disassembler_1.asm
          ./zasm --ixcbr2 test_disassembler_2.asm
      - name: Disassemble the test files
        run: | 
          cd tools
          echo "6" > options.txt
          echo "0" >> options.txt
          # The following calculates the ROM size by subtracting 1 from the file size
          wc -c <test_disassembler_1.rom | awk '{printf "%x\n",  $1 - 1}' >> options.txt
          ../emulator test_disassembler_1.rom > disassembled_1.asm <options.txt
          echo "6" > options.txt
          echo "0" >> options.txt
          # The following calculates the ROM size by subtracting 1 from the file size
          wc -c <test_disassembler_2.rom | awk '{printf "%x\n",  $1 - 1}' >> options.txt
          ../emulator test_disassembler_2.rom > disassembled_2.asm <options.txt
      - name: Remove non-assembly lines
        run: |
          cd tools
          tail -n +12 disassembled_1.asm >disassembled_tail_1.asm
          tail -n +12 disassembled_2.asm >disassembled_tail_2.asm
      - name: Assemble disassembled code
        run: |
          cd tools
          ./zasm --ixcbr2 disassembled_tail_1.asm
          ./zasm --ixcbr2 disassembled_tail_2.asm
      - name: Binary compare the files
        run: |
          cd tools
          cmp disassembled_tail_1.rom test_disassembler_1.rom
          cmp disassembled_tail_2.rom test_disassembler_2.rom
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
