# Test disassembled code produced by the emulator

name: Test Disassembler

on: 
  push:
  workflow_dispatch:
    inputs:
      message:
        description: Message to display in job summary
        required: false
        type: string

jobs:
  test-disassembly: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup emulator and zasm
        run: |
          make
          cd tools
          chmod +x ./zasm
      - name: Assemble, disassemble, compare
        env:
          FILES: test_disassembler_1 test_disassembler_2
        run: |
          cd tools
          for f in $FILES; do
            echo "file basename: ${f}"
            ./zasm --ixcbr2 ${f}.asm
            echo "6" > options.txt
            echo "0" >> options.txt
            # The following calculates the ROM size by subtracting 1 from the file size
            wc -c <${f}.rom | awk '{printf "%x\n",  $1 - 1}' >> options.txt
            echo "options file:"
            cat options.txt
            ../emulator ${f}.rom > ${f}_disassembled.asm <options.txt
            # Strip out the non-assembly top lines of the emulator output
            tail -n +12 ${f}_disassembled.asm >${f}_tail.asm
            ./zasm --ixcbr2 ${f}_tail.asm
            echo "Comparing... ${f}.rom ${f}_tail.rom"
            cmp ${f}.rom ${f}_tail.rom
          done
      - name: Print the job summary
        if: ${{ inputs.message }}
        run: |
          echo ${{ inputs.message }} >$GITHUB_STEP_SUMMARY
